name: Test uploaded codes

on:
  push:
    branches:
      - dev

jobs:
  TEST_COMPONENTS:
    name: Test Components
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Typecheck first
        run: npm run typecheck

      - name: Test components
        run: echo "Test success"
