name: Test uploaded codes

on:
  pull_request
jobs:
  TEST_COMPONENTS:
    name: Test Components
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Typecheck first
        run: npm run typecheck

      - name: Test components
        run: echo "Test success"
